from mentFeatureUtils import genEntCtxMask,genEntMentMask
from ctxFeatureUtils import genEntCtxMask_new
from loadWordEmbed import wordEmbedding
from loadCharacter import CharacterEmbedding
from gen_hier_pos_type import gen_pos_neg_tag,gen_type_pair
#from gen_att_hier_pos_type import gen_pos_neg_tag,gen_type_pair 